language: cpp
sudo: required
dist: trusty
install:
- ./scripts/install_dependencies.sh
script:
- rm -rf build && ./scripts/build.sh Debug   1 && (cd build && make test)
- rm -rf build && ./scripts/build.sh Release 1 && (cd build && make test)
